version: '3'
services:
  frontend:
    image: flaviofrancisco/vagasprajr-web
    networks:
      - vagasprajr-network
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - .env
    build:            
      args:
        - REACT_APP_API_HOST=${REACT_APP_API_HOST}
        - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
        - REACT_APP_GOOGLE_OAUTH_REDIRECT_URI=${REACT_APP_GOOGLE_OAUTH_REDIRECT_URI}
    depends_on:
      - backend
  backend:        
    image: flaviofrancisco/vagasprajr-api
    networks:
      - vagasprajr-network
    container_name: api
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./uploads:/uploads:rw
    depends_on:
      - database
  database:
    image: flaviofrancisco/vagasprajr-db
    networks:
      - vagasprajr-network
    container_name: db
    env_file:
      - .env    
    volumes:
      - ./db:/data/db
      - ./backup:/backup
    ports:
      - "27017:27017" 


networks:
  vagasprajr-network:
        
